<?php

namespace Database\Seeders;

use App\Models\Ciudades;
use App\Models\Provincias;
use Illuminate\Database\Seeder;

class CiudadesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Ciudades::truncate();

        if ($Baja_California = Provincias::where('nombre', 'Baja California')->first()) {
            $Baja_California->ciudades()->createMany([
                ['nombre' => 'Ensenada'],
                ['nombre' => 'Mexicali'],
                ['nombre' => 'Tecate'],
                ['nombre' => 'Tijuana'],
                ['nombre' => 'Playas de Rosarito'],
                ['nombre' => 'San Quintín'],
            ]);
        }

        if ($Ciudad_de_méxico = Provincias::where('nombre', 'Ciudad de méxico')->first()) {
            $Ciudad_de_méxico->ciudades()->createMany([
                ['nombre' => 'Azcapotzalco'],
                ['nombre' => 'Coyoacán'],
                ['nombre' => 'Cuajimalpa de Morelos'],
                ['nombre' => 'Gustavo A. Madero'],
                ['nombre' => 'Iztacalco'],
                ['nombre' => 'Iztapalapa'],
                ['nombre' => 'La Magdalena Contreras'],
                ['nombre' => 'Milpa Alta'],
                ['nombre' => 'Tláhuac'],
                ['nombre' => 'Tlalpan'],
                ['nombre' => 'Xochimilco'],
                ['nombre' => 'Benito Juárez'],
                ['nombre' => 'Cuauhtémoc'],
                ['nombre' => 'Miguel Hidalgo'],
                ['nombre' => 'Venustiano Carranza'],
            ]);
        }

        if ($Estado_de_méxico = Provincias::where('nombre', 'Estado de méxico')->first()) {
            $Estado_de_méxico->ciudades()->createMany([
                ['nombre' => 'Azcapotzalco'],
                ['nombre' => 'Coyoacán'],
                ['nombre' => 'Cuajimalpa de Morelos'],
                ['nombre' => 'Gustavo A. Madero'],
                ['nombre' => 'Iztacalco'],
                ['nombre' => 'Iztapalapa'],
                ['nombre' => 'La Magdalena Contreras'],
                ['nombre' => 'Milpa Alta'],
                ['nombre' => 'Tláhuac'],
                ['nombre' => 'Tlalpan'],
                ['nombre' => 'Xochimilco'],
                ['nombre' => 'Benito Juárez'],
                ['nombre' => 'Cuauhtémoc'],
                ['nombre' => 'Miguel Hidalgo'],
                ['nombre' => 'Venustiano Carranza'],
                ['nombre' => 'Acambay de Ruíz Castañeda'],
                ['nombre' => 'Acolman'],
                ['nombre' => 'Aculco'],
                ['nombre' => 'Almoloya de Alquisiras'],
                ['nombre' => 'Almoloya de Juárez'],
                ['nombre' => 'Almoloya del Río'],
                ['nombre' => 'Amanalco'],
                ['nombre' => 'Amatepec'],
                ['nombre' => 'Amecameca'],
                ['nombre' => 'Apaxco'],
                ['nombre' => 'Atenco'],
                ['nombre' => 'Atizapán'],
                ['nombre' => 'Atizapán de Zaragoza'],
                ['nombre' => 'Atlacomulco'],
                ['nombre' => 'Atlautla'],
                ['nombre' => 'Axapusco'],
                ['nombre' => 'Ayapango'],
                ['nombre' => 'Calimaya'],
                ['nombre' => 'Capulhuac'],
                ['nombre' => 'Coacalco de Berriozábal'],
                ['nombre' => 'Coatepec Harinas'],
                ['nombre' => 'Cocotitlán'],
                ['nombre' => 'Coyotepec'],
                ['nombre' => 'Cuautitlán'],
                ['nombre' => 'Chalco'],
                ['nombre' => 'Chapa de Mota'],
                ['nombre' => 'Chapultepec'],
                ['nombre' => 'Chiautla'],
                ['nombre' => 'Chicoloapan'],
                ['nombre' => 'Chiconcuac'],
                ['nombre' => 'Chimalhuacán'],
                ['nombre' => 'Donato Guerra'],
                ['nombre' => 'Ecatepec de Morelos'],
                ['nombre' => 'Ecatzingo'],
                ['nombre' => 'Huehuetoca'],
                ['nombre' => 'Hueypoxtla'],
                ['nombre' => 'Huixquilucan'],
                ['nombre' => 'Isidro Fabela'],
                ['nombre' => 'Ixtapaluca'],
                ['nombre' => 'Ixtapan de la Sal'],
                ['nombre' => 'Ixtapan del Oro'],
                ['nombre' => 'Ixtlahuaca'],
                ['nombre' => 'Xalatlaco'],
                ['nombre' => 'Jaltenco'],
                ['nombre' => 'Jilotepec'],
                ['nombre' => 'Jilotzingo'],
                ['nombre' => 'Jiquipilco'],
                ['nombre' => 'Jocotitlán'],
                ['nombre' => 'Joquicingo'],
                ['nombre' => 'Juchitepec'],
                ['nombre' => 'Lerma'],
                ['nombre' => 'Malinalco'],
                ['nombre' => 'Melchor Ocampo'],
                ['nombre' => 'Metepec'],
                ['nombre' => 'Mexicaltzingo'],
                ['nombre' => 'Morelos'],
                ['nombre' => 'Naucalpan de Juárez'],
                ['nombre' => 'Nezahualcóyotl Romero'],
                ['nombre' => 'Nopaltepec'],
                ['nombre' => 'Ocoyoacac'],
                ['nombre' => 'Ocuilan'],
                ['nombre' => 'El Oro'],
                ['nombre' => 'Otumba'],
                ['nombre' => 'Otzoloapan'],
                ['nombre' => 'Otzolotepec'],
                ['nombre' => 'Ozumba'],
                ['nombre' => 'Papalotla'],
                ['nombre' => 'La Paz'],
                ['nombre' => 'Polotitlán'],
                ['nombre' => 'Rayón'],
                ['nombre' => 'San Antonio la Isla'],
                ['nombre' => 'San Felipe del Progreso'],
                ['nombre' => 'San Martín de las Pirámides'],
                ['nombre' => 'San Mateo Atenco'],
                ['nombre' => 'San Simón de Guerrero'],
                ['nombre' => 'Santo Tomás'],
                ['nombre' => 'Soyaniquilpan de Juárez'],
                ['nombre' => 'Sultepec'],
                ['nombre' => 'Tecámac'],
                ['nombre' => 'Tejupilco'],
                ['nombre' => 'Temamatla'],
                ['nombre' => 'Temascalapa'],
                ['nombre' => 'Temascalcingo'],
                ['nombre' => 'Temascaltepec'],
                ['nombre' => 'Temoaya'],
                ['nombre' => 'Tenancingo'],
                ['nombre' => 'Tenango del Aire'],
                ['nombre' => 'Tenango del Valle'],
                ['nombre' => 'Teoloyucan'],
                ['nombre' => 'Teotihuacán'],
                ['nombre' => 'Tepetlaoxtoc'],
                ['nombre' => 'Tepetlixpa'],
                ['nombre' => 'Tepotzotlán'],
                ['nombre' => 'Tequixquiac'],
                ['nombre' => 'Texcaltitlán'],
                ['nombre' => 'Texcalyacac'],
                ['nombre' => 'Texcoco'],
                ['nombre' => 'Tezoyuca'],
                ['nombre' => 'Tianguistenco'],
                ['nombre' => 'Timilpan'],
                ['nombre' => 'Tlalmanalco'],
                ['nombre' => 'Tlalnepantla de Baz'],
                ['nombre' => 'Tlatlaya'],
                ['nombre' => 'Toluca'],
                ['nombre' => 'Tonatico'],
                ['nombre' => 'Tultepec'],
                ['nombre' => 'Tultitlán'],
                ['nombre' => 'Valle de Bravo'],
                ['nombre' => 'Villa de Allende'],
                ['nombre' => 'Villa del Carbón'],
                ['nombre' => 'Villa Guerrero'],
                ['nombre' => 'Villa Victoria'],
                ['nombre' => 'Xonacatlán'],
                ['nombre' => 'Zacazonapan'],
                ['nombre' => 'Zacualpan'],
                ['nombre' => 'Zinacantepec'],
                ['nombre' => 'Zumpahuacán'],
                ['nombre' => 'Zumpango'],
                ['nombre' => 'Cuautitlán Izcalli'],
                ['nombre' => 'Valle de Chalco Solidaridad'],
                ['nombre' => 'Luvianos'],
                ['nombre' => 'San José del Rincón'],
                ['nombre' => 'Tonanitla'],
            ]);
        }

        if ($Nuevo_León = Provincias::where('nombre', 'Nuevo León')->first()) {
            $Nuevo_León->ciudades()->createMany([
                ['nombre' => 'Abasolo'],
                ['nombre' => 'Agualeguas'],
                ['nombre' => 'Los Aldamas'],
                ['nombre' => 'Allende'],
                ['nombre' => 'Anáhuac'],
                ['nombre' => 'Apodaca'],
                ['nombre' => 'Aramberri'],
                ['nombre' => 'Bustamante'],
                ['nombre' => 'Cadereyta Jiménez'],
                ['nombre' => 'El Carmen'],
                ['nombre' => 'Cerralvo'],
                ['nombre' => 'Ciénega de Flores'],
                ['nombre' => 'China'],
                ['nombre' => 'Doctor Arroyo'],
                ['nombre' => 'Doctor Coss'],
                ['nombre' => 'Doctor González'],
                ['nombre' => 'Galeana'],
                ['nombre' => 'García'],
                ['nombre' => 'San Pedro Garza García'],
                ['nombre' => 'General Bravo'],
                ['nombre' => 'General Escobedo'],
                ['nombre' => 'General Terán'],
                ['nombre' => 'General Treviño'],
                ['nombre' => 'General Zaragoza'],
                ['nombre' => 'General Zuazua'],
                ['nombre' => 'Guadalupe'],
                ['nombre' => 'Los Herreras'],
                ['nombre' => 'Higueras'],
                ['nombre' => 'Hualahuises'],
                ['nombre' => 'Iturbide'],
                ['nombre' => 'Juárez'],
                ['nombre' => 'Lampazos de Naranjo'],
                ['nombre' => 'Linares'],
                ['nombre' => 'Marín'],
                ['nombre' => 'Melchor Ocampo'],
                ['nombre' => 'Mier y Noriega'],
                ['nombre' => 'Mina'],
                ['nombre' => 'Montemorelos'],
                ['nombre' => 'Monterrey'],
                ['nombre' => 'Pesquería'],
                ['nombre' => 'Los Ramones'],
                ['nombre' => 'Rayones'],
                ['nombre' => 'Sabinas Hidalgo'],
                ['nombre' => 'Salinas Victoria'],
                ['nombre' => 'San Nicolás de los Garza'],
                ['nombre' => 'Hidalgo'],
                ['nombre' => 'Santa Catarina'],
                ['nombre' => 'Santiago'],
                ['nombre' => 'Vallecillo'],
                ['nombre' => 'Villaldama'],
            ]);
        }

        if ($Querétaro = Provincias::where('nombre', 'Querétaro')->first()) {
            $Querétaro->ciudades()->createMany([
                ['nombre' => 'Amealco de Bonfil'],
                ['nombre' => 'Pinal de Amoles'],
                ['nombre' => 'Arroyo Seco'],
                ['nombre' => 'Cadereyta de Montes'],
                ['nombre' => 'Colón'],
                ['nombre' => 'Corregidora'],
                ['nombre' => 'Ezequiel Montes'],
                ['nombre' => 'Huimilpan'],
                ['nombre' => 'Jalpan de Serra'],
                ['nombre' => 'Landa de Matamoros'],
                ['nombre' => 'El Marqués'],
                ['nombre' => 'Pedro Escobedo'],
                ['nombre' => 'Peñamiller'],
                ['nombre' => 'Querétaro'],
                ['nombre' => 'San Joaquín'],
                ['nombre' => 'San Juan del Río'],
                ['nombre' => 'Tequisquiapan'],
                ['nombre' => 'Tolimán'],
            ]);
        }
    }
}
